Rails:
  Enabled: true

AllCops:
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Metrics/LineLength:
  Max: 110

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Layout/IndentArray:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/CollectionMethods:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/deploy.rb
    - config/deploy/*.rb
    - spec/**/*spec.rb
