script: bundle exec rake spec
language: ruby
# cache: bundler
rvm:
- 2.4.1

before_install:
  - umask 022
  - gem install bundler:1.17.3 --no-rdoc --no-ri

before_script:
  - "cp ./config/database.yml.example ./config/database.yml"
  - "cp ./config/gitito.yml.example ./config/gitito.yml"

script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
